// Packs the device model for the firmware.
//   node host/pack_model.mjs
//
// Writes:
//   model/vocab.bin                                 WordPiece vocabulary, sorted for binary search
//   firmware/components/tinydecide/td_meta.h        tensor offsets into model.bin, config, specials
//
// model.bin itself is embedded unchanged (.incbin): its Q4 tensors are a 16-byte aligned nibble plane
// (16 bytes per 32 weights, rows contiguous) plus a bf16 scale plane, which is exactly what
// dot_q4q8_pie(nib_row, xq, scale_row, xs, nb) reads.
//
// vocab.bin: "TDV1", u32 n, u32 blobLen, u32 off[n+1], u16 id[n], blob (bytes, sorted, no terminators).
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url).pathname;
const meta = JSON.parse(readFileSync(root + "model/meta.json", "utf8"));
const T = Object.fromEntries(meta.tensors.map((t) => [t.name, t]));
const need = (n) => { if (!T[n]) throw new Error("missing tensor " + n); return T[n]; };

for (const t of meta.tensors) {
  if (t.dtype === "q4" && (t.offset % 16 || t.scale_offset % 2 || t.shape[1] % 32))
    throw new Error(`Q4 tensor ${t.name} breaks the kernel's alignment rules`);
  if (t.offset % 4) throw new Error(`tensor ${t.name} is not 4-byte aligned`);
}

// ---- vocab.bin
const tk = meta.tokenizer;
if (tk.kind !== "wordpiece" || !tk.lowercase) throw new Error("expected a lowercase WordPiece tokenizer");
const entries = [];
tk.vocab.forEach((p, i) => { if (p !== null && p !== undefined) entries.push([Buffer.from(p, "utf8"), i]); });
entries.sort((a, b) => Buffer.compare(a[0], b[0]));
for (let i = 1; i < entries.length; i++)
  if (Buffer.compare(entries[i - 1][0], entries[i][0]) === 0) throw new Error("duplicate piece " + entries[i][0]);
const n = entries.length, blobLen = entries.reduce((s, e) => s + e[0].length, 0);
const head = Buffer.alloc(12 + 4 * (n + 1) + 2 * n);
head.write("TDV1", 0, "ascii"); head.writeUInt32LE(n, 4); head.writeUInt32LE(blobLen, 8);
let off = 0;
entries.forEach(([b], i) => { head.writeUInt32LE(off, 12 + 4 * i); off += b.length; });
head.writeUInt32LE(off, 12 + 4 * n);
entries.forEach(([, id], i) => head.writeUInt16LE(id, 12 + 4 * (n + 1) + 2 * i));
writeFileSync(root + "model/vocab.bin", Buffer.concat([head, ...entries.map((e) => e[0])]));

// ---- td_meta.h
const c = meta.cfg;
if (c.arch !== "electra" || c.fusion !== "all" || (c.L_a || 0) !== 0) throw new Error("engine supports electra / fusion all / L_a 0");
const q4 = (n) => { const t = need(n); if (t.dtype !== "q4") throw new Error(n + " is not q4"); return `{${t.offset}u, ${t.scale_offset}u, ${t.shape[0]}, ${t.shape[1]}}`; };
const i8 = (n) => { const t = need(n); if (t.dtype !== "int8") throw new Error(n + " is not int8"); return `{${t.offset}u, ${t.scale_offset}u, ${t.shape[0]}, ${t.shape[1]}}`; };
const f32 = (n) => { const t = need(n); if (t.dtype !== "f32") throw new Error(n + " is not f32"); return `${t.offset}u`; };
const ffn = need("m.blocks.0.fc.weight").shape[0];
const blocks = [];
for (let l = 0; l < c.layers; l++) {
  const p = `m.blocks.${l}.`;
  blocks.push(`  {${q4(p + "q.weight")}, ${q4(p + "k.weight")}, ${q4(p + "v.weight")}, ${q4(p + "o.weight")},\n` +
    `   ${q4(p + "fc.weight")}, ${q4(p + "fc2.weight")},\n` +
    `   ${f32(p + "q.bias")}, ${f32(p + "k.bias")}, ${f32(p + "v.bias")}, ${f32(p + "o.bias")}, ${f32(p + "fc.bias")}, ${f32(p + "fc2.bias")},\n` +
    `   ${f32(p + "ln1.weight")}, ${f32(p + "ln1.bias")}, ${f32(p + "ln2.weight")}, ${f32(p + "ln2.bias")}}`);
}
const sp = meta.specials, F = meta.format;
const fl = (x) => { const s = String(Math.fround(x)); return (s.includes(".") || s.includes("e") ? s : s + ".0") + "f"; };
const h = `// GENERATED by host/pack_model.mjs from model/meta.json. Do not edit.
#pragma once
#include <stdint.h>

namespace tdm {

constexpr uint32_t MODEL_BYTES = ${meta.bytes}u;
constexpr int D = ${c.d}, LAYERS = ${c.layers}, HEADS = ${c.heads}, DHEAD = ${c.d / c.heads};
constexpr int EMB = ${c.emb_dim}, FFN = ${ffn}, DH = ${c.dh_head}, VOCAB = ${tk.vocab.length};
constexpr float LN_EPS = ${fl(c.ln_eps)};
constexpr int MAX_CHARS = ${tk.max_chars};

struct Q4 { uint32_t nib, sc; int rows, cols; };   // nibble plane, bf16 scale plane
struct I8 { uint32_t q, sc; int rows, cols; };     // int8 rows, one f32 scale per row

struct Block {
  Q4 q, k, v, o, fc, fc2;
  uint32_t qb, kb, vb, ob, fcb, fc2b;
  uint32_t ln1w, ln1b, ln2w, ln2b;
};

constexpr uint32_t TYPE0 = ${f32("m.type0")};
constexpr Q4 WORD = ${q4("m.word.weight")};
constexpr I8 POS = ${i8("m.posemb.weight")};
constexpr uint32_t ELN_W = ${f32("m.eln.weight")}, ELN_B = ${f32("m.eln.bias")};
constexpr Q4 PROJ = ${q4("m.proj.weight")};
constexpr uint32_t PROJ_B = ${f32("m.proj.bias")};

constexpr Block BLOCKS[LAYERS] = {
${blocks.join(",\n")}
};

constexpr uint32_t H_SCALE = ${f32("h.scale")};
constexpr uint32_t H_NORM_W = ${f32("h.norm.weight")}, H_NORM_B = ${f32("h.norm.bias")};
constexpr I8 H_A0 = ${i8("h.A.0.weight")}, H_O0 = ${i8("h.O.0.weight")}, H_P = ${i8("h.P.weight")};

constexpr int TS_MAX = ${F.ts_max}, P_Q = ${F.p_q}, Q_MAX = ${F.q_max};

constexpr int SP_STATE = ${sp["<|state|>"]}, SP_CHOICE = ${sp["<|choice|>"]}, SP_SEP = ${sp["<|sep|>"]};
constexpr int SP_O = ${sp["<|o|>"]}, SP_ANS = ${sp["<|ans|>"]}, SP_UNK = ${tk.vocab.indexOf(tk.unk)};

constexpr float TEMP[4] = {${meta.temp.map(fl).join(", ")}};
constexpr float BETA[${meta.beta.length}] = {${meta.beta.map(fl).join(", ")}};

}  // namespace tdm
`;
writeFileSync(root + "firmware/components/tinydecide/td_meta.h", h);
console.log(`vocab.bin: ${n} pieces, ${blobLen} B text; td_meta.h: ${c.layers} layers, FFN ${ffn}`);
